Add schema adjustment
Azure/azure-kusto-spark pull request #196
Opened 2021-07-07 06:20 UTC by k-tomak

#### Add KustoSinkOption KUSTO_ADJUST_SCHEMA

_Add write option KUSTO_ADJUST_SCHEMA will automatically validate schema inconsistencies between source DataFrame to write and target Kusto table.
KUSTO_ADJUST_SCHEMA behaviour:_
_- If set 'FailIfNotMatch' adjust schemas equality (column name and order) for DataFrame and target Kusto table, fails if schemas don't match._
_- If set 'NoAdjustment' do nothing._
_- If set 'GenerateDynamicCsvMapping', dynamically generates csv mapping based on DataFrame and target Kusto table column names when writing to Kusto. If some Kusto table fields are missing in the DataFrame, they will be ingested as empty. If some DataFrame fields are missing in target table, fails._
_The existing IngestionMappingReference will be reset._
_Default: 'NoAdjustment'_

---

#### Future Release Comment

**Features:**
- add KustoSinkOption KUSTO_ADJUST_SCHEMA. 
- add KustoSinkSchemaAdjustmentE2E tests

2021-07-08 14:33 UTC, ohadbitt commented
hey
is this ready for review?

2021-07-08 14:39 UTC, k-tomak commented
Yes

чт, 8 июл. 2021 г. в 17:33, ohad bitton ***@***.***>:

> hey
> is this ready for review?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/azure-kusto-spark/pull/196#issuecomment-876491124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWN6VM4DY5EBGLIYW2NRS3TWWZL7ANCNFSM47563VYQ>
> .
>

2021-07-11 09:56 UTC, ohadbitt commented
please merge with latest

2021-07-11 11:19 UTC, ohadbitt reviewed
please add validation on 
setMappingOnStagingTableIfNeeded 
that mapping is not configured on the same time that KUSTO_ADJUST_SCHEMA != NoAdjustment

2021-07-11 12:11 UTC, ohadbitt requested changes

2021-07-11 12:11 UTC, ohadbitt commented on connector/src/main/scala/com/microsoft/kusto/spark/datasink/SparkIngestionProperties.scala
> +      null, // no ingestionProperties additionalProperties getter to extract creationTime value
please refer to my other comment then you wouldnt need this

2021-07-11 12:11 UTC, ohadbitt commented on connector/src/main/scala/com/microsoft/kusto/spark/utils/KustoIngestionUtils.scala
> +      throw new RuntimeException(s"Target table schema does not match to DataFrame schema. " +
We are moving from using RuntimeException - you can see RetriesExhaustedException for example - lets make a new exceptions folder while we are at it and here call all these exceptions SchemaMatchException or something similar

2021-07-11 12:13 UTC, ohadbitt commented on connector/src/test/scala/com/microsoft/kusto/spark/KustoSinkSchemaAdjustmentE2E.scala
> +  "Source DataFrame schema adjustment" should "not adjust" in {
tag all tests with 
taggedAs KustoE2E 
our triggered tests currently dont run the E2E

2021-07-12 09:36 UTC, k-tomak commented
@ohadbitt I've committed all changes for your review

2021-07-12 12:07 UTC, k-tomak commented
About setMappingOnStagingTableIfNeeded. 
IngestionMapping will be updated only if "GenerateDynamicCsvMapping" is set.
When "GenerateDynamicCsvMapping" is set, mappingReferenceName will be reset to Empty, so code block in function setMappingOnStagingTableIfNeeded: 
`if (StringUtils.isNotBlank(mappingReferenceName))`
will be ignored without additional checks.
Or you want to add Exception if user set GenerateDynamicCsvMapping and IngestionMappingReference in SinkOptions simultaneously?

2021-07-13 10:21 UTC, ohadbitt commented
> About setMappingOnStagingTableIfNeeded.
> IngestionMapping will be updated only if "GenerateDynamicCsvMapping" is set.
> When "GenerateDynamicCsvMapping" is set, mappingReferenceName will be reset to Empty, so code block in function setMappingOnStagingTableIfNeeded:
> `if (StringUtils.isNotBlank(mappingReferenceName))`
> will be ignored without additional checks.
> Or you want to add Exception if user set GenerateDynamicCsvMapping and IngestionMappingReference in SinkOptions simultaneously?

Yes i want an exception so user is aware that the mapping he provided is ignored

2021-07-13 13:17 UTC, k-tomak commented
> Yes i want an exception so user is aware that the mapping he provided is ignored
Done

2021-07-15 14:39 UTC, ohadbitt approved these changes

2021-07-18 10:11 UTC, merged